### PR TITLE
MAKE WORKFLOWS GREAT AGAIN!!!

### PR DESCRIPTION
**Pull request by VocalFan**
1. Make all that repeating code be in a bundle ffs.

2. Cleaner code

3. UPDATED ACTION DEPENDENCIES WOOOOO-

4. Automated dev-build numbers!

5. Caching??? Holy shit!

### CODE REVIEW

**Comment by tposejank** [comment]
🤯🤯

**Comment by VocalFan** [comment]
Ayy

**Comment by tposejank** [comment]
Worked greatly on the latest workflow run. Appreciated!

**Comment by VocalFan** [comment]
Mwehehehe

**Comment by VocalFan** [comment]
> Worked greatly on the latest workflow run. Appreciated!

I'd love to help with anything else!

**Comment by VocalFan** [comment]
> Any help is appreciated! 👍

Well, just gimme any asks XD

**Comment by BombasticTom** [comment]
🦅🦅🦅

**Pull request merged**
